// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa1pZADDIkV9ZFsELpVtbe0VvC9TEiBFg',
    appId: '1:62899042835:web:7f8c8eb9d345d8d460dde6',
    messagingSenderId: '62899042835',
    projectId: 'wheere-abb78',
    authDomain: 'wheere-abb78.firebaseapp.com',
    storageBucket: 'wheere-abb78.appspot.com',
    measurementId: 'G-VQWJRT55QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ-WzjSJ31rN0-Vk3MOI9coaOljuHyK2Y',
    appId: '1:62899042835:android:b217aaaf6833a18660dde6',
    messagingSenderId: '62899042835',
    projectId: 'wheere-abb78',
    storageBucket: 'wheere-abb78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDMbyLfCGuj9nnkMHYKcjhQ8IBy8VJHlA',
    appId: '1:62899042835:ios:4731afec5532301660dde6',
    messagingSenderId: '62899042835',
    projectId: 'wheere-abb78',
    storageBucket: 'wheere-abb78.appspot.com',
    iosClientId: '62899042835-bu7b58tu5cibgjn8jdo29631g4pcqjl5.apps.googleusercontent.com',
    iosBundleId: 'kr.ac.kumoh.sjjpl138.wheere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDMbyLfCGuj9nnkMHYKcjhQ8IBy8VJHlA',
    appId: '1:62899042835:ios:4731afec5532301660dde6',
    messagingSenderId: '62899042835',
    projectId: 'wheere-abb78',
    storageBucket: 'wheere-abb78.appspot.com',
    iosClientId: '62899042835-bu7b58tu5cibgjn8jdo29631g4pcqjl5.apps.googleusercontent.com',
    iosBundleId: 'kr.ac.kumoh.sjjpl138.wheere',
  );
}
